-- 用户信息表
DROP TABLE IF EXISTS DB_12306.USERINFO;
CREATE TABLE IF NOT EXISTS DB_12306.USERINFO (
	USER_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '用户ID',
	LOGIN_NAME VARCHAR(50) NOT NULL COMMENT '登录用户',
	LOGIN_PASS VARCHAR(50) NOT NULL COMMENT '登录密码',
	APPID VARCHAR(50) COMMENT '应用ID',
	COOKIE VARCHAR(100) COMMENT 'COOKIE',
	USER_NAME VARCHAR(50) COMMENT '用户姓名',
	NICK_NAME VARCHAR(50) COMMENT '用户昵称',
	VERIFICATION_TYPE INT COMMENT '验证类型',
	VERIFICATION_LINK VARCHAR(100) COMMENT '验证链接',
	VERIFICATION_CODE VARCHAR(50) COMMENT '验证码',
	LOGIN_STATUS INT COMMENT '登录状态',
	LOGIN_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '登录时间'
);