ticket_map = {
    '0': {'field_name': 'SECRET_KEY', 'comment': '安全秘钥', 'remark': '下单时使用'},
    '1': {'field_name': 'DESC', 'comment': '描述', 'remark': '例如-预定/列车停运/几点起售'},
    '2': {'field_name': 'TRAIN_NO', 'comment': '列车号', 'remark': '查票价时用'},
    '3': {'field_name': 'TRAIN_CODE', 'comment': '车次', 'remark': '列车名称'},
    '4': {'field_name': 'START_STATION_CODE', 'comment': '起始站代码', 'remark': '列车起始站'},
    '5': {'field_name': 'END_STATION_CODE', 'comment': '终点站代码', 'remark': '列车终点站'},
    '6': {'field_name': 'FROM_STATION_CODE', 'comment': '出发站代码', 'remark': '本次搜索起始站'},
    '7': {'field_name': 'TO_STATION_CODE', 'comment': '到达站代码', 'remark': '本次搜索终点站'},
    '8': {'field_name': 'FROM_TIME', 'comment': '出发时间', 'remark': ''},
    '9': {'field_name': 'TO_TIME', 'comment': '到达时间', 'remark': ''},
    '10': {'field_name': 'SPEND_TIME', 'comment': '经历时间', 'remark': ''},
    '11': {'field_name': 'CAN_BUY', 'comment': '是否可以购买-Y/N', 'remark': ''},
    '12': {'field_name': '', 'comment': '', 'remark': ''},
    '13': {'field_name': 'START_DATE', 'comment': '列车起始站发车日期', 'remark': ''},
    '14': {'field_name': '', 'comment': '', 'remark': ''},
    '15': {'field_name': 'TRAIN_LOCATION', 'comment': '', 'remark': ''},
    '16': {'field_name': 'FROM_STATION_NO', 'comment': '出发站站序', 'remark': '01表示始发站，大于1表示过站'},
    '17': {'field_name': 'TO_STATION_NO', 'comment': '到达站站序', 'remark': ''},
    '18': {'field_name': 'IS_SUPPORT_CARD', 'comment': '可否使用二代身份证进出站', 'remark': '0-否/1-是'},
    '19': {'field_name': '', 'comment': '', 'remark': ''},
    '20': {'field_name': '', 'comment': '', 'remark': ''},
    '21': {'field_name': 'HIGH_SOFT_SLEEP_COUNT', 'comment': '高级软卧等数量', 'remark': ''},
    '22': {'field_name': 'OTHER', 'comment': '其他', 'remark': ''},
    '23': {'field_name': 'SOFT_SLEEP_COUNT', 'comment': '软卧/一等卧 数量', 'remark': ''},
    '24': {'field_name': 'SOFT_SEAT_COUNT', 'comment': '软座数量', 'remark': ''},
    '25': {'field_name': 'SPECIAL_SEAT_COUNT', 'comment': '特等座数量', 'remark': ''},
    '26': {'field_name': 'NONE_SEAT_COUNT', 'comment': '无座数量', 'remark': ''},
    '27': {'field_name': 'YB_COUNT', 'comment': '无座数量', 'remark': ''},
    '28': {'field_name': 'HARD_SLEEP_COUNT', 'comment': '硬卧/二等卧 数量', 'remark': ''},
    '29': {'field_name': 'HARD_SEAT_COUNT', 'comment': '硬座数量', 'remark': ''},
    '30': {'field_name': 'SECOND_SEAT_COUNT', 'comment': '二等座数量', 'remark': ''},
    '31': {'field_name': 'FIRST_SEAT_COUNT', 'comment': '一等座数量', 'remark': ''},
    '32': {'field_name': 'BUSINESS_SEAT_COUNT', 'comment': '商务座/特等座 数量', 'remark': ''},
    '33': {'field_name': 'MOTOR_SLEEP_COUNT', 'comment': '动卧数量', 'remark': ''},
    '34': {'field_name': '', 'comment': '', 'remark': ''},
    '35': {'field_name': 'SEAT_TYPES', 'comment': '查询车票价格时的字段', 'remark': ''},
    '36': {'field_name': '', 'comment': '', 'remark': ''},
    '37': {'field_name': 'CAN_BACKUP', 'comment': '是否支持候补', 'remark': '0-不支持/1-支持'},
    '38': {'field_name': '', 'comment': '', 'remark': ''},
    '39': {'field_name': '', 'comment': '', 'remark': ''},
    '40': {'field_name': '', 'comment': '', 'remark': ''},
    '41': {'field_name': '', 'comment': '', 'remark': ''},
    '42': {'field_name': '', 'comment': '', 'remark': ''},
    '43': {'field_name': '', 'comment': '', 'remark': ''},
    '44': {'field_name': '', 'comment': '', 'remark': ''},
    '45': {'field_name': '', 'comment': '', 'remark': ''},
    '46': {'field_name': '', 'comment': '', 'remark': ''},
    '47': {'field_name': '', 'comment': '', 'remark': ''},
    '48': {'field_name': '', 'comment': '', 'remark': ''},
    '49': {'field_name': '', 'comment': '', 'remark': ''},
    '50': {'field_name': '', 'comment': '', 'remark': ''},
    '51': {'field_name': '', 'comment': '', 'remark': ''},
    '52': {'field_name': '', 'comment': '', 'remark': ''}
}