# 请求地址
url:
  check_url: 'https://kyfw.12306.cn/passport/web/checkLoginVerify'
  login_url: 'https://kyfw.12306.cn/passport/web/login'
  user_login_url: 'https://kyfw.12306.cn/otn/login/userLogin'
  query_ticket_url: 'https://kyfw.12306.cn/otn/leftTicket/queryZ'
  buy_pre_submit_order_url: 'https://kyfw.12306.cn/otn/leftTicket/submitOrderRequest'
  buy_pre_buy_select_seat_init_dc_url: 'https://kyfw.12306.cn/otn/confirmPassenger/initDc'
  buy_pre_get_passenger_info_url: 'https://kyfw.12306.cn/otn/confirmPassenger/getPassengerDTOs'
  buy_pre_check_order_info_url: 'https://kyfw.12306.cn/otn/confirmPassenger/checkOrderInfo'
  buy_pre_get_queue_count_url: 'https://kyfw.12306.cn/otn/confirmPassenger/getQueueCount'

# 请求头
headers:
  Connection: 'keep-alive'
  Content-Type: 'application/json; charset=UTF-8'
  User-Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'

# 登录信息
login:
  # 用户名
  username: '18121177504'
  # 密码
  password: 'lanyue0910'
  # appid
  appid: 'otn'

# 查询
query:
  # 出发日期
  train_date: '2023-09-26'
  from_station: 'SJP'
  to_station: 'BXP'
  purpose_codes: 'ADULT'

# 购买信息
buy:
  # 购买前-获取车票详情
  pre:
    # 出发日期
    train_date: '2023-09-26'
    # 出发地
    query_from_station_name: '石家庄'
    # 目的地
    query_to_station_name: '北京西'
    # 成人/儿童票标识
    purpose_codes: 'ADULT'