# 登录信息
login:
  # 用户名
  username: '18132094376'
  # 密码
  password: 'lanyue0910'
  # appid
  appid: 'otn'
# 自定义购票属性
custom:
  # 乘车人
  user_name: '胡淋婧'
  # 出发日期
  train_date: '2023-10-08'
  # 车票发售时间
  ticket_sale_time: '2023-09-24 14:41:00'
  # 出发站
  query_from_station_name: '高平东'
  from_station: 'GVF'
  # 到达站
  query_to_station_name: '石家庄'
  to_station: 'SJP'
  # 车次号
  station_train_code: 'G684'
  # 座位类型
  # 一等座-M、二等座-O
  seat_type: 'O'
  # 车票类型
  # 1-成人票、2-儿童票、4-残军票
  ticket_type: '1'
  # 乘车人类型-成年人
  purpose_codes: 'ADULT'
  # 车票服务=dc-单程
  tour_flag: 'dc'
